baseURL = "/"
defaultContentLanguage = "uk"
defaultContentLanguageInSubdir = false 
title = "Kaldi"
languageCode = "uk"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg"]

[languages]

[languages.uk]
  languageName = "UA"
  weight = 1
  contentDir = "content/uk"
  languageCode = "uk"

[languages.ru]
  languageName = "RU"
  weight = 2
  contentDir = "content/ru"
  languageCode = "ru"
