baseURL = "/"
defaultContentLanguage = "uk"
defaultContentLanguageInSubdir = true
title = "Kaldi"
languageCode = "uk"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg"]

[languages]

[languages.uk]
  languageName = "Українська"
  weight = 1
  contentDir = "content/uk"

[languages.ru]
  languageName = "Русский"
  weight = 2
  contentDir = "content/ru"
