backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "img"

collections:

  # Посты: uk
  - name: "posts-uk"
    label: "Блог (укр)"
    folder: "site/content/uk/post"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Опис", name: "description", widget: "text", required: false}
      - {label: "Зображення", name: "image", widget: "image", required: false}
      - {label: "Тіло", name: "body", widget: "markdown"}

  # Посты: ru
  - name: "posts-ru"
    label: "Блог (рус)"
    folder: "site/content/ru/post"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Описание", name: "description", widget: "text", required: false}
      - {label: "Изображение", name: "image", widget: "image", required: false}
      - {label: "Тело", name: "body", widget: "markdown"}

  # Все страницы: uk
  - name: "pages-uk"
    label: "Сторінки (укр)"
    folder: "site/content/uk"
    create: false
    slug: "{{slug}}"
    extension: "md"
    identifier_field: "title"
    nested:
      depth: 2
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string", required: false}
      - {label: "Зображення", name: "image", widget: "image", required: false}
      - {label: "Тіло", name: "body", widget: "markdown", required: false}

  # Все страницы: ru
  - name: "pages-ru"
    label: "Страницы (рус)"
    folder: "site/content/ru"
    create: false
    slug: "{{slug}}"
    extension: "md"
    identifier_field: "title"
    nested:
      depth: 2
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Подзаголовок", name: "subtitle", widget: "string", required: false}
      - {label: "Изображение", name: "image", widget: "image", required: false}
      - {label: "Тело", name: "body", widget: "markdown", required: false}

  # Настройки сайта
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: "Footer"
        name: "footer"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: text}
      - file: "site/hugo.toml"
        label: "Hugo Config"
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
